export const card = [
  {
    title: 'Frontend',
    description:
      'I build responsive, accessible, and interactive user interfaces using modern frontend frameworks. I focus on component-driven architecture, state management, performance, and clean UX.',
    techStack: [
      'React',
      'Next.js (App Router)',
      'TypeScript',
      'Tailwind CSS',
      'shadcn/ui',
      'Zustand',
      'Framer Motion',
      'Zod (Form Validation)',
    ],
  },
  {
    title: 'Backend',
    description:
      'I develop scalable and secure backend systems with well-structured APIs, real-time features, and robust authentication. I focus on reliability, data integrity, and clean architecture.',
    techStack: [
      'Node.js',
      'Express.js',
      'REST APIs',
      'WebSockets (Socket.IO)',
      'PostgreSQL',
      'MongoDB',
      'Prisma ORM',
      'JWT Authentication',
      'OAuth',
    ],
  },
  {
    title: 'AI & Integrations',
    description:
      'I integrate AI-powered features and third-party services to enhance user experience, automation, and decision-making within applications.',
    techStack: [
      'OpenAI API',
      'Cohere API',
      'Google Gemini API',
      'Third-party APIs',
      'Authentication Integrations',
    ],
  },
  {
    title: 'Other Skills',
    description:
      'I work with modern tools and workflows that improve collaboration, deployment, testing, and long-term maintainability.',
    techStack: ['Git', 'GitHub', 'Vercel', 'Postman', 'Agile Workflow'],
  },
];

export const projects = [
  {
    name: 'Recruitment Platform',
    description:
      'A website for GDG onCampus to recruit students as members annually.',
    github: 'https://github.com/RamitVishwakarma/RecruitmentPlatformV2Frontend',
    link: 'https://recruitments.gdscjss.in/',
    video: 'https://youtu.be/70uWukMPLec',
    thumbnail: '/images/recplat.png',
    brief: 'team',
    workedOn: 'FullStack',
    techStack: [
      'Next.js- Frontend',
      'typescript',
      'Tailwind CSS',
      'ShadCN',
      'Vercel',
      'Radix UI',
      'motion',
      'html2canvas',
      'zod',
      'zustand',
      'axios',
      'Node.js',
      'Express.js',
      'prisma',
      'PostgreSQL',
      'bcrypt',
      'jsonwebtoken',
      'multer',
      'nodemailer',
      'aws-sdk',
      'swagger UI',
    ],
  },
  {
    name: 'ResumeAI',
    description:
      'An AI-powered platform that helps users optimize their careers through resume building, interview prep, job matching, and cover letter generation.',
    github: 'https://github.com/tanuagarwal-dev/resume-ai',
    link: 'https://resume-ai-v1.vercel.app',
    video: 'https://youtu.be/KZKrtUAluu4',
    thumbnail: '/images/resumeai.png',
    brief: 'solo',
    workedOn: 'FullStack',
    techStack: [
      'Next.js',
      'React',
      'TypeScript',
      'Tailwind CSS',
      'ShadCN UI',
      'Clerk',
      'Google Gemini AI',
      'Prisma',
      'PostgreSQL',
      'Inngest',
      'Vercel',
      'Node.js',
    ],
  },
  {
    name: 'TradeCraft',
    description:
      'A full-stack stock trading platform for managing holdings, executing trades, and tracking real-time market data.',
    github: 'https://github.com/tanuagarwal-dev/StockTrading',
    link: 'https://stocktrading-domain.com',
    video: 'https://youtu.be/os6xYMMZLoc',
    thumbnail: '/images/trade.png',
    brief: 'solo',
    workedOn: 'FullStack',
    techStack: [
      'Next.js',
      'TypeScript',
      'Tailwind CSS',
      'Chart.js',
      'Vercel',
      'Node.js',
      'Express.js',
      'MongoDB',
      'Mongoose',
      'JWT',
      'Bcrypt',
      'Passport.js',
      'Axios',
      'React Context API',
    ],
  },
  {
    name: 'LOLly',
    description:
      "A fun project to search and take AI's help to create fun memes with just a prompt.",
    link: 'https://meme-ify.vercel.app/',
    video: 'https://youtu.be/K4v14ja_BeU',
    thumbnail: '/images/lolly.png',
    brief: 'solo',
    github: 'https://github.com/tanuagarwal-dev/meme-ify',
    workedOn: 'FullStack',
    techStack: [
      'Next.js- Frontend',
      'Next.js- Backend',
      'Cohere API',
      'DreamStudio API:  for image generation',
      'typescript',
      'Google Search API',
      'Tailwind CSS',
      'ShadCN',
      'motion',
      'html2canvas',
      'Vercel',
    ],
  },
  {
    name: 'Compliment Extension',
    description:
      'A delightful AI-powered Chrome extension that gives users daily boosts of joy, confidence, or sass with customizable vibes and streak tracking.',
    link: 'https://github.com/tanuagarwal-dev/compliments-extension',
    github: 'https://github.com/tanuagarwal-dev/compliments-extension',
    video: 'https://youtu.be/tuLBFl0g2_8',
    thumbnail: '/images/complement.png',
    brief: 'solo',
    workedOn: 'Frontend + Extension + Backend',
    techStack: [
      'HTML',
      'CSS',
      'JavaScript',
      'Chrome Extensions API',
      'chrome.storage.local',
      'Node.js',
      'Express.js',
      'Cohere API',
    ],
  },
];

export const noteworthyProjects = [
  //   {
  //   name: 'AI Mentor',
  //   description: 'An AI-powered mentorship platform with real-time chat and personalized learning paths.',
  //   github: 'https://github.com/tanu-agarwal0101/AIMentorFrontend',
  //   link: '', // Add deployed link when ready
  //   video: '', // Add demo video if available
  //   thumbnail: '/images/aimentor.png',
  //   brief: 'personal',
  //   workedOn: 'FullStack',
  //   techStack: [
  //     'Next.js',
  //     'TypeScript',
  //     'Tailwind CSS',
  //     'Node.js',
  //     'Express.js',
  //     'Prisma ORM',
  //     'PostgreSQL',
  //     'OpenAI API',
  //     'Socket.io',
  //     'JWT Authentication',
  //     'Axios',
  //   ],
  // },

  {
    name: 'AI Mentor',
    description:
      'An AI-powered mentorship platform with real-time chat and personalized learning dashboards.',
    link: 'https://github.com/tanu-agarwal0101/AIMentorBackend',
    github: 'https://github.com/tanu-agarwal0101/AIMentorFrontend',
    image: '/images/aimentor.png',
    brief: 'solo- ongoing',
    workedOn: 'Fullstack Development',
    techStack: [
      'Next.js',
      'TypeScript',
      'Tailwind CSS',
      'Node.js',
      'Express.js',
      'Prisma ORM',
      'PostgreSQL',
      'OpenAI API',
      'Socket.io',
      'JWT Authentication',
      'Axios',
    ],
  },
  {
    name: 'HerGuardian',
    description:
      'A safety-focused web application built with security and reliability at its core.',
    link: 'https://github.com/tanuagarwal-dev/her-guardian-backend-v1',
    github: 'https://github.com/tanuagarwal-dev/her-guardian-frontend-v1',
    image: '/images/herguardian.png',
    brief: 'solo- ongoing',
    workedOn: 'Fullstack Development',
    techStack: [
      'Next.js',
      'Tailwind CSS',
      'Express.js',
      'Node.js',
      'ShadCN',
      'Socket.io',
      'axios',
      'Cohere API',
      'typescript',
      'Prisma ORM',
      'MongoDB',
      'motion',
      'Nodemailer',
    ],
  },
  {
    name: 'Briefly',
    description:
      'A chrome extension that uses AI to record meetings, summarize them, and capture snapshots of important images and show in gallery.',
    link: 'https://meeting-minutes-nine.vercel.app',
    github: 'https://github.com/krshishir1/meeting-minutes',
    image: '/images/briefly.png',
    brief: 'team: HackVSIT 6.0',
    workedOn: 'Frontend Development',
    techStack: [
      'Next.js',
      'Tailwind CSS',
      'MongoDB',
      'typescript',
      'ShadCN',
      'Express.js',
      'Node.js',
      'Vercel',
      'motion',
      'axios',
    ],
  },
];
