export const card = [
  {
    title: 'Frontend',
    description:
      'I specialize in building responsive, interactive, and user-friendly interfaces using modern frontend technologies. I focus on clean design, accessibility, and performance.',
    techStack: [
      'React',
      'Next.js',
      'Tailwind CSS',
      'TypeScript',
      'JavaScript',
      'ShadCN UI',
    ],
  },
  {
    title: 'Backend',
    description:
      'I have experience developing scalable and secure backend systems, REST APIs, and real-time features. I work with modern frameworks and databases to deliver reliable solutions.',
    techStack: [
      'Node.js',
      'Express.js',
      'MongoDB',
      'PostgreSQL',
      'Prisma ORM',
      'Supabase',
      'Firebase',
    ],
  },
  {
    title: 'AI & Integrations',
    description:
      'I enjoy integrating AI-powered features and third-party services into applications, leveraging APIs to enhance user experience and automation.',
    techStack: ['OpenAI API', 'Cohere API', 'Socket.IO', 'REST APIs', 'OAuth'],
  },
  {
    title: 'Other Skills',
    description:
      'Beyond core development, I work with tools and practices that improve collaboration, deployment, and maintainability.',
    techStack: ['Git', 'GitHub', 'Vercel', 'Zod', 'Postman', 'Agile Workflow'],
  },
];

export const projects = [
  {
    name: 'Recruitment Platform',
    description:
      'A website for GDG onCampus to recruit students as members annually.',
    github: 'https://github.com/RamitVishwakarma/RecruitmentPlatformV2Frontend',
    link: 'https://recruitments.gdscjss.in/',
    video: '/video/recplat_video.mp4',
    thumbnail: '/images/recplat.png',
    brief: 'team',
    workedOn: 'FullStack',
    techStack: [
      'Next.js- Frontend',
      'typescript',
      'Tailwind CSS',
      'ShadCN',
      'Vercel',
      'Radix UI',
      'motion',
      'html2canvas',
      'zod',
      'zustand',
      'axios',
      'Node.js',
      'Express.js',
      'prisma',
      'PostgreSQL',
      'bcrypt',
      'jsonwebtoken',
      'multer',
      'nodemailer',
      'aws-sdk',
      'swagger UI',
    ],
  },
  {
    name: 'LOLly',
    description:
      "A fun project to search and take AI's help to create fun memes with just a prompt.",
    link: 'https://meme-ify.vercel.app/',
    video: '/video/lolly_video.mp4',
    thumbnail: '/images/lolly.png',
    brief: 'solo',
    github: 'https://github.com/tanuagarwal-dev/meme-ify',
    workedOn: 'FullStack',
    techStack: [
      'Next.js- Frontend',
      'Next.js- Backend',
      'Cohere API',
      'DreamStudio API:  for image generation',
      'typescript',
      'Google Search API',
      'Tailwind CSS',
      'ShadCN',
      'motion',
      'html2canvas',
      'Vercel',
    ],
  },
  {
    name: 'Compliment Extension',
    description:
      'A delightful AI-powered Chrome extension that gives users daily boosts of joy, confidence, or sass with customizable vibes and streak tracking.',
    link: 'https://github.com/tanuagarwal-dev/compliment-extension',
    github: 'https://github.com/tanuagarwal-dev/compliment-extension',
    video: '/video/complements_video.mp4',
    thumbnail: '/images/complement.png',
    brief: 'solo',
    workedOn: 'Frontend + Extension + Backend',
    techStack: [
      'HTML',
      'CSS',
      'JavaScript',
      'Chrome Extensions API',
      'chrome.storage.local',
      'Node.js',
      'Express.js',
      'Cohere API',
    ],
  },
];

export const noteworthyProjects = [
  {
    name: 'Briefly',
    description:
      'A chrome extension that uses AI to record meetings, summarize them, and capture snapshots of important images and show in gallery.',
    link: 'https://meeting-minutes-nine.vercel.app',
    github: 'https://github.com/krshishir1/meeting-minutes',
    image: '/images/briefly.png',
    brief: 'team: HackVSIT 6.0',
    workedOn: 'Frontend Development',
    techStack: [
      'Next.js',
      'Tailwind CSS',
      'MongoDB',
      'typescript',
      'ShadCN',
      'Express.js',
      'Node.js',
      'Vercel',
      'motion',
      'axios',
    ],
  },
  {
    name: 'HerGuardian',
    description:
      'A safety-focused web application built with security and reliability at its core.',
    link: 'https://github.com/tanuagarwal-dev/her-guardian-backend-v1',
    github: 'https://github.com/tanuagarwal-dev/her-guardian-frontend-v1',
    image: '/images/herguardian.png',
    brief: 'solo- ongoing',
    workedOn: 'Fullstack Development',
    techStack: [
      'Next.js',
      'Tailwind CSS',
      'Express.js',
      'Node.js',
      'ShadCN',
      'Socket.io',
      'axios',
      'Cohere API',
      'typescript',
      'Prisma ORM',
      'MongoDB',
      'motion',
      'Nodemailer',
    ],
  },
];
